[versions]
# build tools
java = "17"
jacoco = "0.8.8"

[libraries]
# build tools
gradle-nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version = "1.1.0" }
# dependencies
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.5" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "24.0.0" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "1.33" }
gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
jimfs = { module = "com.google.jimfs:jimfs", version = "1.2" }
icu4j = { module = "com.ibm.icu:icu4j", version = "72.1" }
# test dependencies
spock-core = { module = "org.spockframework:spock-core", version = "2.3-groovy-4.0" }
awaitility = { module = "org.awaitility:awaitility", version = "4.2.0" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.4.5" }
